import type { Metadata } from "next";
import { Inter } from "next/font/google";

import AuthNavbar from "@/components/AuthNavbar";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple Auth System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <AuthNavbar />
      {children}
    </>
  );
}
